language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt
script:
  - cargo build --all-features
  - cargo test --all-features
  - cargo fmt --all -- --check